project:
  type: website
  output-dir: docs

website:
  title: "Aidan Astridge"
  search: false
  navbar:
    title: false
    image: https://eps.leeds.ac.uk/images/Honey_bees.jpg
    background: white
    right:
      - text: "GitHub" 
        href: https://github.com/aidanastridge
      - text: "LinkedIn" 
        href: https://www.linkedin.com/in/aidanastridge/
      - text: "Twitter" 
        href: https://twitter.com/aidanastridge
       

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-title: Contents
    anchor-sections: false
    toc-depth: 3
    linkcolor: "#4F200D"

editor: visual

